name: Build and Push Docker Image for UI

on:
  push:
    branches:
      - main  # Execute o workflow quando houver push na branch main
  pull_request:
    branches:
      - main  # Execute o workflow em pull requests na branch main

env:
  REGISTRY: docker.io
  IMAGE_NAME: yuritech/client-managemente-ui

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/{{ env.IMAGE_NAME }}:latest
