name: Build and Push Docker Image for UI and Deploy to AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: yuritech/client-management-ui

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/yuritech/client-management-ui:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Definir as variáveis de ambiente diretamente no script
            REGISTRY="${{ env.REGISTRY }}"
            IMAGE_NAME="${{ env.IMAGE_NAME }}"
            
            # Baixar a nova imagem do Docker Hub
            docker pull $REGISTRY/$IMAGE_NAME:latest
            
            # Parar o contêiner em execução, se houver
            docker stop frontend || true
            docker rm frontend || true
            
            # Iniciar o novo contêiner com o mapeamento correto de portas
            docker run -d --name frontend -p 80:4000 $REGISTRY/$IMAGE_NAME:latest
